name: energy_modeling

channels:
  - default
  - conda-forge

dependencies:
  - pip
  - python>=3.8
  - numpy
  - scipy
  - pandas
  - matplotlib
  - tqdm
  - pip:
    - ipython
    - notebook
    - pulp